# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Math Tutoring
tagline:             'SAT, ACT, Common Core'
description:         'Experienced tutoring that emphasizes developing intuition, reasoning logically, and recognizing patterns, rather than  ineffective rote memorization'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Arjun Panickssery
  url:               https://arjunpanickssery.github.io
  email:             arjun.panickssery@gmail.com

# Custom vars
version:             1.0.0
