# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Arjun Panickssery
tagline:             'Storing Pages and stuff'
description:         'Stuff'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Arjun Panickssery
  url:               https://arjunpanickssery.github.io
  email:             arjun.panickssery@gmail.com

# Custom vars
version:             1.0.0
